import Cocoa

// generated by GPT-4o

func setMultiplePasteboardItems() {
	let pasteboard = NSPasteboard.general
	pasteboard.clearContents()

	let item1 = NSPasteboardItem()
	item1.setString("First string", forType: .string)

	let item2 = NSPasteboardItem()
	item2.setString("Second string", forType: .string)

	pasteboard.writeObjects([item1, item2])
}

setMultiplePasteboardItems()
